name: Auto PR to main

on:
  push:
    branches-ignore: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Open or update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: 'chore: merge `${{ github.ref_name }}` → main'
          body: |
            Auto-opened PR for `${{ github.ref_name }}`.

            - CI runs on PRs
            - Image builds but **does not deploy** unless manually triggered
          labels: |
            ci
            auto-pr
          draft: false
          commit-message: 'chore: sync `${{ github.ref_name }}` to PR'
