name: Auto PR from dev → main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Open/Update PR dev → main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'dev'
          destination_branch: 'main'
          pr_title: 'Auto: merge dev → main'
          pr_body: |
            This PR was opened automatically when commits landed on **dev**.
            - CI must be green before merge (enforced by branch protections)
            - No deploy is triggered by this workflow
          pr_label: 'auto-pr'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          pr_allow_empty: false
          pr_draft: false
