name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  server:
    name: Server (Rust) – fmt • clippy • test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show versions
        run: |
          rustc -V
          cargo -V

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test --all --all-features --no-fail-fast

      - name: Panic redirect script – smoke test
        working-directory: .
        run: |
          set -euxo pipefail
          chmod +x ./panic.sh
          # Write logs into repo's server/exports so they persist in workspace
          M3_EXPORTS_DIR="$GITHUB_WORKSPACE/server/exports" ./panic.sh
          # Assert at least one panic log was created
          find server/exports/panic -type f -name '*.log' -print -quit | grep -q .
