name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  server:
    name: Server (Rust ${{ matrix.toolchain }}) – fmt • clippy • test
    strategy:
      matrix:
        toolchain: [stable, nightly]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Show versions
        run: |
          rustc -V
          cargo -V

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test --all --all-features --no-fail-fast

      - name: Panic redirect script – smoke test
        working-directory: .
        run: |
          set -euxo pipefail
          chmod +x ./panic.sh
          # Write logs into repo's server/exports so they persist in workspace
          M3_EXPORTS_DIR="$GITHUB_WORKSPACE/server/exports" ./panic.sh
          # Assert at least one panic log was created
          find server/exports/panic -type f -name '*.log' -print -quit | grep -q .

  ui:
    name: UI (Node) – fmt • lint • build
    strategy:
      matrix:
        node: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Verify pnpm availability (and fallback via Corepack)
        run: |
          set -euxo pipefail
          which pnpm || true
          pnpm -v || true
          # Fallback to Corepack in case the action didn't inject pnpm in PATH
          corepack enable
          corepack prepare pnpm@9 --activate
          which pnpm
          pnpm -v

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Format (workspace)
        run: pnpm fmt

      - name: Lint (workspace)
        run: pnpm lint

      - name: Build UI
        working-directory: ui
        run: pnpm build

  whisper:
    name: Whisper Guard – commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify whispers in commits
        shell: bash
        run: |
          set -euo pipefail

          if [ -f scripts/commit-whisper-check.mjs ]; then
            echo "Checking commit whispers…"
          else
            echo "scripts/commit-whisper-check.mjs not found; skipping." && exit 0
          fi

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            range="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
            shas=$(git rev-list --no-merges "$range")
          else
            shas=$(git rev-list -n 1 HEAD)
          fi

          if [ -z "$shas" ]; then
            echo "No commits found in range; skipping." && exit 0
          fi

          status=0
          for sha in $shas; do
            git log -1 --pretty=%B "$sha" > .git/commitmsg.txt
            echo "\n— checking $sha —" && head -n 3 .git/commitmsg.txt || true
            node scripts/commit-whisper-check.mjs .git/commitmsg.txt || status=$?
          done

          exit $status
