name: PR Housekeeping

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - name: Add helpful labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            needs-review

  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: 'package-lock.json yarn.lock pnpm-lock.yaml Cargo.lock'

  welcome:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Thanks for the PR! CI will build a preview image. Deployment is **disabled** by default for privacy. :lock:"
            })
